# Generated by Django 6.0.7 on 2026-07-31 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitbit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fitbit_code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('IN_USE', 'In Use'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='FREE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('access_token_expiration', models.DateTimeField()),
                ('authentication_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('estimated_end_date', models.DateTimeField(blank=True, null=True)),
                ('real_end_date', models.DateTimeField(blank=True, null=True)),
                ('fitbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='google_health.fitbit')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='google_health.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('SYNC_ERROR', 'Error de sincronización'), ('NO_DATA_24H', 'Sin datos >24 horas'), ('DEVICE_OFF', 'Pulsera apagada'), ('LOW_BATTERY', 'Batería <20%'), ('TOKEN_EXPIRED', 'Token caducado'), ('DEVICE_UNLINKED', 'Dispositivo desvinculado'), ('NO_RECORDS', 'Participante sin registros'), ('HRV_UNAVAILABLE', 'HRV no disponible'), ('INSUFFICIENT_SLEEP', 'Sueño insuficiente'), ('INSUFFICIENT_USAGE', 'Tiempo de uso insuficiente')], max_length=50)),
                ('priority', models.CharField(blank=True, choices=[('HIGH', 'Alta'), ('MEDIUM', 'Media')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='google_health.assignment')),
                ('google_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='google_health.googleaccount')),
            ],
        ),
        migrations.AddField(
            model_name='googleaccount',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_account', to='google_health.participant'),
        ),
        migrations.CreateModel(
            name='PhysiologicalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variable_type', models.CharField(choices=[('SLEEP', 'Sueño'), ('SLEEP_DURATION', 'Duración total del sueño'), ('SLEEP_LIGHT', 'Minutos en sueño ligero'), ('SLEEP_DEEP', 'Minutos en sueño profundo'), ('SLEEP_REM', 'Minutos en sueño REM'), ('SLEEP_AWAKE', 'Tiempo despierto durante el periodo de sueño'), ('SLEEP_START_END', 'Hora de inicio y finalización del sueño'), ('HEART_RATE', 'Frecuencia cardíaca'), ('HEART_RATE_RESTING', 'Frecuencia cardíaca en reposo'), ('HRV_NOCTURNAL', 'Variabilidad de la frecuencia cardíaca nocturna'), ('RESPIRATORY_RATE_NOCTURNAL', 'Frecuencia respiratoria nocturna'), ('HR_ZONE_FAT_BURN', 'Minutos en zona de quema de grasa'), ('HR_ZONE_CARDIO', 'Minutos en zona cardio'), ('HR_ZONE_PEAK', 'Minutos en zona pico'), ('ACTIVE_ZONE_MINUTES', 'Minutos activos (Active Zone Minutes)'), ('STEPS', 'Pasos'), ('DISTANCE', 'Distancia')], max_length=100)),
                ('physical_time', models.DateTimeField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('metric_value', models.FloatField()),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('recording_method', models.CharField(blank=True, max_length=100, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physiological_data', to='google_health.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=100)),
                ('downloaded_records', models.IntegerField(default=0)),
                ('google_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='google_health.googleaccount')),
            ],
        ),
    ]
