# Generated by Django 6.0.7 on 2026-08-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
