# Generated by Django 6.0.7 on 2026-08-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_health', '0002_participant_email_participant_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleaccount',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='googleaccount',
            name='access_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googleaccount',
            name='authentication_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='googleaccount',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
