# Generated by Django 6.0.7 on 2026-08-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_health', '0003_alter_googleaccount_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiologicaldata',
            name='metric_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
