# Generated by Django 6.0.7 on 2026-08-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_health', '0004_alter_physiologicaldata_metric_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiologicaldata',
            name='variable_type',
            field=models.CharField(choices=[('SLEEP_DURATION', 'Duración total del sueño'), ('SLEEP_LIGHT', 'Minutos en sueño ligero'), ('SLEEP_DEEP', 'Minutos en sueño profundo'), ('SLEEP_REM', 'Minutos en sueño REM'), ('SLEEP_AWAKE', 'Tiempo despierto durante el periodo de sueño'), ('SLEEP_START', 'Hora de inicio del sueño'), ('SLEEP_END', 'Hora de finalización del sueño'), ('SLEEP_MINUTES_TO_FALL_ASLEEP', 'Minutos hasta que te duermes'), ('HEART_RATE', 'Frecuencia cardíaca'), ('HEART_RATE_RESTING', 'Frecuencia cardíaca en reposo'), ('HRV_NOCTURNAL', 'Variabilidad de la frecuencia cardíaca nocturna'), ('HRV_RMSSD', 'Variaciones rápidas entre latidos consecutivos (RMSSD)'), ('HRV_ENTROPY', 'Desorden/aleatoriedad del sistema (entropía)'), ('RESPIRATORY_RATE_NOCTURNAL', 'Frecuencia respiratoria nocturna'), ('HR_ZONE_FAT_BURN', 'Minutos en zona de quema de grasa'), ('HR_ZONE_CARDIO', 'Minutos en zona cardio'), ('HR_ZONE_PEAK', 'Minutos en zona pico'), ('ACTIVE_ZONE_MINUTES', 'Minutos activos (Active Zone Minutes)'), ('STEPS', 'Pasos'), ('DISTANCE', 'Distancia')], max_length=100),
        ),
    ]
