# Generated by Django 6.0.7 on 2026-08-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_health', '0005_alter_physiologicaldata_variable_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiologicaldata',
            name='variable_type',
            field=models.CharField(choices=[('SLEEP_DURATION', 'Duración total del sueño'), ('SLEEP_LIGHT', 'Minutos en sueño ligero'), ('SLEEP_DEEP', 'Minutos en sueño profundo'), ('SLEEP_REM', 'Minutos en sueño REM'), ('SLEEP_AWAKE', 'Tiempo despierto durante el periodo de sueño'), ('SLEEP_START', 'Hora de inicio del sueño'), ('SLEEP_END', 'Hora de finalización del sueño'), ('SLEEP_MINUTES_TO_FALL_ASLEEP', 'Minutos hasta que te duermes'), ('SLEEP_MINUTES_ASLEEP', 'Minutos reales dormidos'), ('SLEEP_AFTER_WAKE_UP', 'Minutos despierto tras levantarse'), ('RESPIRATORY_RATE_NOCTURNAL', 'Frecuencia respiratoria global (respiraciones/min)'), ('RESPIRATORY_RATE_LIGHT', 'Frecuencia respiratoria en sueño ligero'), ('RESPIRATORY_RATE_DEEP', 'Frecuencia respiratoria en sueño profundo'), ('RESPIRATORY_RATE_REM', 'Frecuencia respiratoria en sueño REM'), ('HEART_RATE', 'Frecuencia cardíaca'), ('HEART_RATE_RESTING', 'Frecuencia cardíaca en reposo'), ('HRV_AVERAGE_MS', 'Promedio de variabilidad cardíaca (ms)'), ('HRV_RMSSD', 'RMSSD en sueño profundo (ms)'), ('HRV_NON_REM_HR', 'Frecuencia cardíaca en sueño no-REM (bpm)'), ('HRV_ENTROPY', 'Entropía de la variabilidad cardíaca'), ('HR_ZONE_FAT_BURN', 'Minutos en zona de quema de grasa'), ('HR_ZONE_CARDIO', 'Minutos en zona cardio'), ('HR_ZONE_PEAK', 'Minutos en zona pico'), ('ACTIVE_ZONE_MINUTES', 'Minutos activos (Active Zone Minutes)'), ('STEPS', 'Pasos'), ('DISTANCE', 'Distancia')], max_length=100),
        ),
    ]
