# Generated by Django 6.0.7 on 2026-08-27 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_health', '0006_alter_physiologicaldata_variable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='alert',
            name='first_detected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_detected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Media')], max_length=20),
        ),
    ]
