const en = {
  translation: {
    // Menu & Roles (App.tsx)
    "Participants": "Participants",
    "Fitbit": "Fitbit",
    "Assignments": "Assignments",
    "Physiological Data": "Physiological Data",
    "Alerts": "Alerts",
    "Exports": "Exports",
    "Syncs": "Syncs",
    "Roles & Permissions": "Roles & Permissions",
    "Logout": "Log out",
    "Administrator": "Administrator",
    "Researcher": "Researcher",
    "ADMINISTRATION": "ADMINISTRATION",
    "RESEARCH": "RESEARCH",

    // FrontPage
    "Login": "Sign in",
    "FrontCardTitle": "University of Seville",
    "Main Title Line 1": "Emotional Health and ",
    "Main Title Line 2": "Neuroscience for the",
    "Main Title Line 3": "Development of Andalusia",
    "Subtitle": "Project of the Department of Experimental Psychology and Social Psychology of the University of Seville",
    "About SENDA": "About SENDA",
    "Platform": "Platform",
    "Research": "Research",
    "Discover SENDA": "Discover SENDA",
    "About SENDA text": "SENDA is a research project promoted by the Department of Experimental Psychology and Social Psychology of the University of Seville, funded by the CENTRA Foundation.",
    "Registered Participants": "Participants",
    "Registered Fitbits": "Fitbits",
    "Records": "Records",
    "FooterText": "University of Seville · Foundation CENTRA",
    "Secure Access": "Secure access · GDPR compliance",
    "Dark Mode": "Dark Mode",
    "Light Mode": "Light Mode",
    "Toggle Light Mode": "Switch to light mode",
    "Toggle Dark Mode": "Switch to dark mode",
    "Lang ES Alt": "Spanish",
    "Lang EN Alt": "English",
    "Hero Title Line1": "Emotional Health and Neuroscience",
    "Hero Title Line2": "for the Development of Andalusia",
    "About Heading": "Research against chronic stress and for emotional wellbeing",
    "About SENDA text 2": "The platform automates the acquisition and management of physiological variables through Fitbit Charge 6 devices and the Google Health API, facilitating scientific analysis.",
    "Research Image Alt": "Scientific research",
    "Pre Wearable Phase": "Pre-wearable phase",
    "Pillar1 Title": "Emotional health",
    "Pillar1 Text": "An innovative approach to chronic stress and psychological wellbeing in high emotional-demand groups in Andalusia.",
    "Pillar2 Title": "Neuroscience",
    "Pillar2 Text": "Integration of objective records such as heart rate variability (HRV) for accurate assessment.",
    "Pillar3 Title": "Health Platform",
    "Pillar3 Text": "A centralized technological environment for automated synchronization via the Google Health API and Fitbit Charge 6.",
    "Data Overline": "Objective physiological data",
    "Data Heading": "From participant to scientific analysis.",
    "Data Text": "SENDA continuously collects key health metrics through integration with the Google Health API.",
    "Metric HRV": "Heart Rate Variability (HRV)",
    "Metric Sleep": "Sleep (Stages and RMSSD)",
    "Metric HeartRate": "Heart Rate",
    "Metric Activity": "Activity and Steps",
    "Wearable Official": "Wearable",
    "Wearable Image Alt": "Wearable device used in research",
    "Platform Heading Pre": "Full control of the study,",
    "Platform Heading Highlight": " in a single platform",
    "Platform Text": "SENDA integrates a layered architecture for the comprehensive management of participants, devices and automatic synchronizations.",
    "Feature1 Title": "Participants and Accounts",
    "Feature1 Text": "Individualized management per participant.",
    "Feature2 Title": "Device Inventory",
    "Feature2 Text": "Operational control of Fitbit Charge 6 devices.",
    "Feature3 Title": "Physiological Data",
    "Feature3 Text": "Structured acquisition of sleep, HRV, heart rate, activity, among others.",
    "Feature4 Title": "Rotational Traceability",
    "Feature4 Text": "Tracking of the lifecycle and temporary assignment of bracelets.",
    "Feature5 Title": "Alert System",
    "Feature5 Text": "Automatic detection of inactive devices, low battery and out-of-range values.",
    "Feature6 Title": "Analytical Export",
    "Feature6 Text": "Generation of CSV and Excel files.",
    "Research Overline": "Connected research",
    "Research Heading Line1": "From device to",
    "Research Heading Line2": "scientific knowledge",
    "Research Text": "Full automation through background tasks to extract and structure data without manual intervention.",
    "Step1 Title": "Fitbit Charge 6",
    "Step1 Subtitle": "Continuous non-invasive monitoring",
    "Step2 Title": "Google Health API",
    "Step2 Subtitle": "Synchronization via OAuth 2.0",
    "Step3 Title": "SENDA Platform",
    "Step3 Subtitle": "Secure storage in PostgreSQL",
    "Banner Overline": "Public Health and Wellbeing",
    "Banner Heading": "Prevention of chronic stress and improvement of emotional health in Andalusia",
    "Monitor Title": "Study Monitoring",
    "Monitor Subtitle": "Device and alert status",
    "Monitor Active": "Active",
    "Monitor Alert Title": "Automatic notice",
    "Monitor Alert Badge": "Alert",
    "Monitor Alert Text": "Detection of low battery, inactive devices (24h) or atypical physiological values.",
    "Monitor Sync Title": "Secure OAuth 2.0 synchronization",
    "Monitor Sync Text": "Unattended access token renewal.",
    "Monitor Overline": "Traceability",
    "Monitor Heading": "Rotational study under control",
    "Monitor Text": "Centralized supervision of the bracelet inventory, temporary assignments and incident control for the research team.",
    "Checklist1": "Unattended synchronization through automatic background tasks",
    "Checklist2": "Strict control of incidents, token errors and traceability",
    "Checklist3": "Centralized information ready for analysis by the research team",
    "Institutions Overline": "University research",
    "Institutions Heading": "A project of the University of Seville",
    "Institutions Text": "SENDA was created within the Department of Experimental Psychology and Social Psychology at the University of Seville, funded by the Centro de Estudios Andaluces Foundation (CENTRA).",
    "Faculty Logo Alt": "Faculty of Psychology, University of Seville",
    "CTA Heading": "Biomarkers and technology for more connected research.",
    "CTA Text": "Access the internal SENDA research platform for study management and physiological data analysis.",
    "CTA Sync 24_7": "Continuous synchronization",
    "CTA Security": "Google security",
    "Fitbit Image Alt": "Fitbit Charge 6",

    // Login
    "Admin Access": "Exclusive access for administrators.",
    "Enter your username": "Enter your username",
    "Researcher Step 1": "Enter your authorized email.",
    "Researcher Step 2": "Enter the temporary code received.",
    "Admin User": "Admin user",
    "Researcher Email": "Researcher email",
    "Temporary Code": "Single-use temporary code",
    "Change Email or Code": "Change email or resend code?",
    "Password": "Password",
    "Role": "Role",
    "Request Code": "Request verification code",
    "Access System": "Access system",
    "Processing": "Processing...",
    "Back to home": "Back to home",
    "Health": "Health",
    "Emotional": "Emotional",
    "Neuroscience": "Neuroscience",
    "Development": "Development",
    "Andalusia": "Andalusia",

    // Participants
    "Participants Title": "Participants",
    "Enrolled People": "people enrolled in the study",
    "Register Participant": "Register participant",
    "Search Participant": "Search by code or email...",
    "Code": "CODE",
    "Email": "EMAIL",
    "Access Token": "ACCESS TOKEN",
    "Refresh Token": "REFRESH TOKEN",
    "Token Expiration": "TOKEN EXPIRATION",
    "No token": "No token",
    "No token info": "No token info",
    "Add Participant": "Add participant",
    "Message": "After saving, the system will redirect to Google OAuth to link the account with the",
    "Password Placeholder": "···········",
    "Cancel": "Cancel",
    "Save Participant": "Save participant",
    "Participant Detail": "Participant detail",
    "Full Info": "Complete information and access tokens of the participant.",
    "Delete Participant": "Delete participant",
    "Reconnect Google": "Reconnect Google",
    "Close": "Close",
    "Authorization Completed": "Authorization completed",
    "Error loading participants": "Could not load participants",
    "Authorization success": "Authorization successful! Account successfully linked to code",
    "No email": "No email",
    "Valid email error": "Enter a valid email.",
    "Password error": "Enter a password.",
    "Create participant error": "Could not create participant.",
    "Participant created": "Participant successfully created. Redirecting to Google Health...",
    "Server connection error": "Error connecting to server.",
    "Not available": "Not available",
    "Delete confirmation": "Delete participant",
    "Authorization Completed Title": "Authorization completed",
    "No participants found": "No participants found",

    // Fitbits
    "Fitbit Title": "Fitbit",
    "Devices Registered": "devices registered in the study",
    "Register Fitbit": "Register Fitbit",
    "Register New Fitbit Subtitle": "Assign a new Fitbit device to the system",
    "In Use": "In use",
    "Free": "Free",
    "Maintenance": "Maintenance",
    "Inactive": "Inactive",
    "Search Fitbit": "Search by Fitbit code or status...",
    "Status": "STATUS",
    "Register New Fitbit": "Register new Fitbit",
    "Automatic Code": "Device code (Automatic)",
    "Operational Status": "Operational status",
    "Save Fitbit": "Save Fitbit",
    "Fitbit Detail": "Fitbit detail",
    "Fitbit Full Info": "Complete information of the selected device.",
    "Delete Fitbit": "Delete Fitbit",
    "Error loading fitbits": "Could not load fitbits",
    "Create fitbit error": "Could not register bracelet",
    "Fitbit registered": "Fitbit successfully registered.",
    "No Fitbits found": "No devices found.",
    "Delete Fitbit Confirmation": "Delete bracelet",
    "Delete Fitbit error": "Could not delete bracelet",

    // Assignments
    "Assignments Title": "Assignments",
    "Assignments Registered": "assignments registered in the study",
    "New Assignment": "Register new assignment",
    "New Assignment Subtitle": "Assign a Fitbit device to a participant",
    "Search Assignment": "Search by participant code, Fitbit or status...",
    "Start Date": "START DATE",
    "Estimated End Date": "ESTIMATED END DATE",
    "Real End Date": "REAL END DATE",
    "Select Participant": "Select a participant",
    "Select Fitbit": "Select a Fitbit",
    "Save Assignment": "Save assignment",
    "Edit Assignment": "Edit assignment",
    "Modify": "Modify",
    "Save Changes": "Save changes",
    "Delete Assignment": "Delete assignment",
    "Error loading assignments": "Could not load assignments",
    "Create assignment error": "Could not create assignment",
    "Assignment created successfully": "Assignment successfully created.",
    "Update assignment error": "Could not update assignment",
    "In Progress": "In progress",
    "No assignments found": "No assignments found.",
    "Select Participant Label": "Participant Code",
    "Select a participant": "Select a participant",
    "Select Fitbit Label": "Fitbit Code",
    "Select a bracelet": "Select a bracelet",
    "Real End Date Optional": "Real End Date (optional)",
    "Edit Assignment Subtitle": "Modify the necessary assignment fields.",
    "Assignment Detail": "Assignment Detail",
    "Assignment Detail Subtitle": "Complete information of the selected assignment.",
    "Delete Assignment Confirmation": "Delete assignment for",
    "Activa": "Active",
    "Completada": "Completed",

    // Physiological Data
    "Physiological Data Title": "Physiological Data",
    "Physiological Subtitle": "View, filter and analyze monitoring history",
    "All": "All",
    "Active": "Active",
    "Completed": "Completed",
    "Export CSV": "Export to CSV",
    "Export Excel": "Export to Excel",
    "Clear Filters": "Clear filters",
    "From": "From",
    "To": "To",
    "Detailed Records": "Detailed records",
    "Showing Filtered Records": "Showing {{count}} of {{total}} filtered records",
    "Variable": "VARIABLE",
    "Time": "TIME",
    "Value": "VALUE",
    "Previous": "← Previous",
    "Next": "Next →",
    "Page": "Page {{page}} of {{totalPages}}",
    "No Physiological Data": "No data found for the selected filters.",
    "Selected plural": "selected",
    "Clear selection": "Clear selection",
    "All (Clear selection)": "All (Clear selection)",
    "No results found": "No results found",
    "Error loading physiological data": "Could not load physiological data",
    "Search Variable": "Search variable...",
    "unit_min": "min",
    "unit_bpm": "bpm",
    "unit_resp": "breaths/min",
    "unit_ms": "ms",
    "unit_km": "km",
    "unit_steps": "steps",

    // Alerts
    "Alerts Title": "Alerts & Notifications",
    "Alerts Subtitle": "Automatic device monitoring.",
    "Active Count": "Active ({{count}})",
    "Resolved History": "Resolved History",
    "Critical": "CRITICAL",
    "Warnings": "WARNINGS",
    "Active Tray": "Active incidents tray",
    "Resolved Tray": "Resolved incidents history",
    "Per Page": "per page",
    "Resolve": "Resolve",
    "Resolved": "Resolved",
    "No Alerts": "No alerts registered.",
    "Error loading alerts": "Could not load alerts",
    "Error resolving alert": "Could not resolve alert",
    "SYNC_ERROR_title": "Sync Error",
    "SYNC_ERROR_msg": "Could not synchronize participant data. Check the connection and try again.",
    "NO_DATA_24H_title": "No data >24 hours",
    "NO_DATA_24H_msg": "No data has been received from the participant in the last 24 hours. Check that the bracelet is being used and synchronized correctly.",
    "DEVICE_OFF_title": "Device off",
    "DEVICE_OFF_msg": "The bracelet appears to be off or inactive. Ask the participant to turn it on and sync with the Fitbit app.",
    "LOW_BATTERY_title": "Battery <20%",
    "LOW_BATTERY_msg": "The bracelet battery is below 20%. It is recommended to recharge the device to avoid data loss.",
    "TOKEN_EXPIRED_title": "Token expired",
    "TOKEN_EXPIRED_msg": "Participant data cannot be accessed. It is necessary to re-authorize the connection with Google Health.",
    "DEVICE_UNLINKED_title": "Device unlinked",
    "DEVICE_UNLINKED_msg": "The bracelet is no longer linked to the participant's account. Check Fitbit and Google Health settings.",
    "NO_RECORDS_title": "Participant without records",
    "NO_RECORDS_msg": "No recorded data exists for this participant. Check that the linking process completed successfully.",
    "HRV_UNAVAILABLE_title": "HRV unavailable",
    "HRV_UNAVAILABLE_msg": "Could not obtain heart rate variability (HRV) for this day. This may be due to insufficient sleep wear time or inadequate signal quality.",
    "INSUFFICIENT_SLEEP_title": "Insufficient sleep",
    "INSUFFICIENT_SLEEP_msg": "Insufficient sleep time was recorded to obtain all physiological metrics.",
    "INSUFFICIENT_USAGE_title": "Insufficient usage time",
    "INSUFFICIENT_USAGE_msg": "The bracelet was used for less than 18 hours during the day. Some physiological variables may be incomplete.",

    // Exports
    "Exports Title": "Exports",
    "Exports Subtitle": "Download global datasets for statistical analysis.",
    "Export Notice": "To export specific ranges or participants, use the advanced filters in the",
    "Participants Resource": "PARTICIPANTS",
    "Participants Desc": "Complete listing and information.",
    "Fitbits Resource": "FITBITS",
    "Fitbits Desc": "Fitbit status and assignment.",
    "Syncs Resource": "SYNCS",
    "Syncs Desc": "Download history and errors.",
    "Assignments Resource": "ASSIGNMENTS",
    "Assigments Desc": "Assignment history and device usage.",
    "Alerts Resource": "ALERTS",
    "Alerts Desc": "Automatic incident supervision.",
    "Researchers Resource": "RESEARCHERS",
    "Researchers Desc": "List of authorized accounts in the system.",
    "Download CSV": "Download CSV",
    "Download Excel": "Download Excel",
    "Modal Title": "Export Filters:",
    "Modal Subtitle": "Select the parameters to refine the file download",
    "Study Status": "Study Status",
    "All participants": "All participants",
    "All status": "All status",
    "All Fitbits": "All Fitbits",
    "All alarm types": "All alarm types",
    "All priorities": "All priorities",
    "Status assignment": "Status assignment",
    "Synchronization date": "Synchronization date",
    "Alarm type": "Alarm type",
    "Priority": "Priority",
    "Detected": "Detected",
    "High": "High",
    "Medium": "Medium",
    "Download Filtered File": "Download Filtered File",
    "Latest Downloads": "Latest downloads",
    "Logs History Desc": "History of the last {{count}} exported files.",
    "Clear History": "Clear history",
    "Resource": "Resource",
    "Format": "Format",
    "Date and Time": "Date and Time",
    "Action": "Action",
    "No Downloads": "No recent download records.",
    "Records Count": "records",

    // Syncs
    "Syncs Title": "Syncs",
    "Syncs Subtitle": "Download history from Google Health API and status of each attempt.",
    "Clear History Btn": "Clear history",
    "Update Data": "Update data",
    "Updating": "Updating...",
    "Success Metric": "SUCCESSES",
    "Error Metric": "ERRORS",
    "Total Metric": "TOTAL PROCESSES",
    "Successes": "Successes",
    "Errors": "Errors",
    "Sync ID": "LOG ID",
    "Account": "ACCOUNT",
    "Start": "START",
    "Result": "RESULT",
    "No Syncs": "No syncs found with the applied filters.",
    "Error loading syncs": "Could not load syncs",
    "Clear history confirmation": "Are you sure you want to clear the entire synchronization history? This action cannot be undone.",
    "Clear history error": "Could not clear history",
    "No account": "No account",
    "Search Sync": "Search by email account or result...",

    // Admin
    "Admin Title": "Manage Researchers",
    "Admin Subtitle": "Exclusive admin panel: authorize emails and manage researcher accounts.",
    "Researcher Email Input": "Researcher email",
    "Authorize Btn": "Authorize and verify email",
    "Authorized Researchers": "Authorized Researchers",
    "Accounts Registered": "registered accounts",
    "Created": "CREATED",
    "Pending": "Pending",
    "No Researchers": "No registered researchers.",
    "Error loading researchers": "Could not load researchers",
    "Create researcher error": "Could not register researcher",
    "Email sent to researcher": "Email sent to researcher with email:",
    "pending acceptance": "pending acceptance",
    "Delete researcher confirmation": "Are you sure you want to delete the researcher",
    "Delete researcher error": "Could not delete researcher",
    "Researcher deleted successfully": "Researcher successfully deleted",
    "Delete Researcher": "Delete researcher"
  }
};

export default en;