const es = {
  translation: {
    // Menú y Roles
    "Participants": "Participantes",
    "Fitbit": "Fitbit",
    "Assignments": "Asignaciones",
    "Physiological Data": "Datos fisiológicos",
    "Alerts": "Alertas",
    "Exports": "Exportaciones",
    "Syncs": "Sincronizaciones",
    "Roles & Permissions": "Roles y Permisos",
    "Logout": "Cerrar sesión",
    "Administrator": "Administrador",
    "Researcher": "Investigador",
    "ADMINISTRATION": "ADMINISTRACIÓN",
    "RESEARCH": "INVESTIGACIÓN",

    // FrontPage 
    "Login": "Iniciar sesión",
    "FrontCardTitle": "Universidad de Sevilla",
    "Main Title Line 1": "Salud Emocional y ",
    "Main Title Line 2": "Neurociencia para el ",
    "Main Title Line 3": "Desarrollo de Andalucía",
    "Subtitle": "Proyecto del Departamento de Psicología Experimental y Psicología Social de la Universidad de Sevilla",
    "About SENDA": "Sobre SENDA",
    "Platform": "Plataforma",
    "Research": "Investigación",
    "Discover SENDA": "Descubrir SENDA",
    "About SENDA text": "SENDA es un proyecto de investigación impulsado por el Departamento de Psicología Experimental y Psicología Social de la Universidad de Sevilla, financiado por la Fundación CENTRA.",
    "Registered Participants": "Participantes",
    "Registered Fitbits": "Fitbits",
    "Records": "Registros",
    "FooterText": "Universidad de Sevilla · Fundación CENTRA",
    "Secure Access": "Acceso protegido · Cumplimiento RGPD",
    "Dark Mode": "Modo Oscuro",
    "Light Mode": "Modo Claro",
    "Toggle Light Mode": "Cambiar a modo claro",
    "Toggle Dark Mode": "Cambiar a modo oscuro",
    "Lang ES Alt": "Español",
    "Lang EN Alt": "Inglés",
    "Hero Title Line1": "Salud Emocional y Neurociencia",
    "Hero Title Line2": "para el Desarrollo de Andalucía",
    "About Heading": "Investigación contra el estrés crónico y por el bienestar emocional",
    "About SENDA text 2": "La plataforma automatiza la adquisición y gestión de variables fisiológicas a través de dispositivos Fitbit Charge 6 y Google Health API, facilitando el análisis científico.",
    "Research Image Alt": "Investigación científica",
    "Pre Wearable Phase": "Fase previa a wearable",
    "Pillar1 Title": "Salud emocional",
    "Pillar1 Text": "Abordaje innovador del estrés crónico y el bienestar psicológico en colectivos de alta demanda emocional en Andalucía.",
    "Pillar2 Title": "Neurociencia",
    "Pillar2 Text": "Integración de registros objetivos como la variabilidad de la frecuencia cardíaca (VFC) para la evaluación precisa.",
    "Pillar3 Title": "Plataforma de salud",
    "Pillar3 Text": "Entorno tecnológico centralizado para la sincronización automatizada mediante Google Health API y Fitbit Charge 6.",
    "Data Overline": "Datos fisiológicos objetivos",
    "Data Heading": "Del participante al análisis científico.",
    "Data Text": "SENDA recopila de forma continua métricas clave de salud mediante la integración con Google Health API.",
    "Metric HRV": "Variabilidad Cardíaca (HRV)",
    "Metric Sleep": "Sueño (Fases y RMSSD)",
    "Metric HeartRate": "Frecuencia Cardíaca",
    "Metric Activity": "Actividad y Pasos",
    "Wearable Official": "Wearable",
    "Wearable Image Alt": "Dispositivo wearable utilizado en investigación",
    "Platform Heading Pre": "Control total del estudio,",
    "Platform Heading Highlight": " en una sola plataforma",
    "Platform Text": "SENDA integra arquitectura en capas para la gestión integral de participantes, dispositivos y sincronizaciones automáticas.",
    "Feature1 Title": "Participantes y Cuentas",
    "Feature1 Text": "Gestión individualizada por participante.",
    "Feature2 Title": "Inventario de Dispositivos",
    "Feature2 Text": "Control operativo de dispositivos Fitbit Charge 6.",
    "Feature3 Title": "Datos Fisiológicos",
    "Feature3 Text": "Adquisición estructurada de sueño, HRV, frecuencia cardíaca, actividad, entre otras.",
    "Feature4 Title": "Trazabilidad Rotativa",
    "Feature4 Text": "Seguimiento del ciclo de vida y asignación temporal de pulseras.",
    "Feature5 Title": "Sistema de Alertas",
    "Feature5 Text": "Detección automática de dispositivos inactivos, batería baja y valores fuera de rango.",
    "Feature6 Title": "Exportación Analítica",
    "Feature6 Text": "Generación de ficheros CSV y Excel.",
    "Research Overline": "Investigación conectada",
    "Research Heading Line1": "Del dispositivo al",
    "Research Heading Line2": "conocimiento científico",
    "Research Text": "Automatización completa mediante tareas en segundo plano para extraer y estructurar los datos sin intervención manual.",
    "Step1 Title": "Fitbit Charge 6",
    "Step1 Subtitle": "Monitorización continua no invasiva",
    "Step2 Title": "Google Health API",
    "Step2 Subtitle": "Sincronización mediante OAuth 2.0",
    "Step3 Title": "Plataforma SENDA",
    "Step3 Subtitle": "Almacenamiento seguro en PostgreSQL",
    "Banner Overline": "Salud Pública y Bienestar",
    "Banner Heading": "Prevención del estrés crónico y mejora de la salud emocional en Andalucía",
    "Monitor Title": "Monitorización de Estudio",
    "Monitor Subtitle": "Estado de dispositivos y alertas",
    "Monitor Active": "Activo",
    "Monitor Alert Title": "Aviso automático",
    "Monitor Alert Badge": "Alerta",
    "Monitor Alert Text": "Detección de batería baja, dispositivos sin actividad (24h) o valores fisiológicos atípicos.",
    "Monitor Sync Title": "Sincronización segura OAuth 2.0",
    "Monitor Sync Text": "Renovación desatendida de tokens de acceso.",
    "Monitor Overline": "Trazabilidad",
    "Monitor Heading": "Estudio rotativo bajo control",
    "Monitor Text": "Supervisión centralizada del inventario de pulseras, asignaciones temporales y control de incidencias para el equipo investigador.",
    "Checklist1": "Sincronización desatendida mediante tareas automáticas en segundo plano",
    "Checklist2": "Control estricto de incidencias, errores de token y trazabilidad",
    "Checklist3": "Información centralizada y lista para el análisis del equipo investigador",
    "Institutions Overline": "Investigación universitaria",
    "Institutions Heading": "Un proyecto de la Universidad de Sevilla",
    "Institutions Text": "SENDA nace en el Departamento de Psicología Experimental y Psicología Social de la Universidad de Sevilla, con el financiamiento de la Fundación Centro de Estudios Andaluces (CENTRA).",
    "Faculty Logo Alt": "Facultad de Psicología Universidad de Sevilla",
    "CTA Heading": "Biomarcadores y tecnología para una investigación más conectada.",
    "CTA Text": "Accede a la plataforma interna de investigación SENDA para la gestión de estudios y análisis de datos fisiológicos.",
    "CTA Sync 24_7": "Sincronización continua",
    "CTA Security": "Seguridad Google",
    "Fitbit Image Alt": "Fitbit Charge 6",

    // Login
    "Sign in": "Iniciar sesión",
    "Admin Access": "Acceso exclusivo para administradores.",
    "Researcher Step 1": "Introduce tu correo autorizado.",
    "Researcher Step 2": "Introduce el código temporal recibido.",
    "Admin User": "Usuario administrador",
    "Enter your username": "Introduce tu usuario",
    "Researcher Email": "Correo investigador/a",
    "Temporary Code": "Código temporal de un solo uso",
    "Change Email or Code": "¿Cambiar correo o reenviar código?",
    "Password": "Contraseña",
    "Role": "Rol",
    "Request Code": "Solicitar código de verificación",
    "Access System": "Acceder al sistema",
    "Processing": "Procesando...",
    "Back to home": "Volver al inicio",
    "Health": "Salud",
    "Emotional": "Emocional",
    "Neuroscience": "Neurociencia",
    "Development": "Desarrollo",
    "Andalusia": "Andalucía",

    // Participants
    "Participants Title": "Participantes",
    "Enrolled People": "personas inscritas en el estudio",
    "Register Participant": "Registrar participante",
    "Search Participant": "Buscar por código o correo...",
    "Code": "CÓDIGO",
    "Email": "CORREO",
    "Access Token": "TOKEN ACCESO",
    "Refresh Token": "TOKEN ACTUALIZACIÓN",
    "Token Expiration": "CADUCIDAD TOKEN ACCESO",
    "No token": "Sin token",
    "No token info": "Sin información de token",
    "Add Participant": "Añadir participante",
    "Message": "Tras guardar, el sistema redigirá a Google OAuth para vincular la cuenta con",
    "Password Placeholder": "···········",
    "Cancel": "Cancelar",
    "Save Participant": "Guardar participante",
    "Participant Detail": "Detalle de participante",
    "Full Info": "Información completa y tokens de acceso del participante.",
    "Delete Participant": "Eliminar participante",
    "Reconnect Google": "Reconectar Google",
    "Close": "Cerrar",
    "Authorization Completed": "Autorización completada",
    "Error loading participants": "No se pudieron cargar los participantes",
    "Authorization success": "¡Autorización exitosa! Cuenta vinculada correctamente al código",
    "No email": "Sin correo",
    "Valid email error": "Introduce un correo válido.",
    "Password error": "Introduce una contraseña.",
    "Create participant error": "No se pudo crear el participante.",
    "Participant created": "Participante creado correctamente. Redirigiendo a Google Health...",
    "Server connection error": "Error al conectar con el servidor.",
    "Not available": "No disponible",
    "Delete confirmation": "¿Eliminar participante",
    "Authorization Completed Title": "Autorización completada",
    "No participants found": "No se encontraron participantes",

    // Fitbits
    "Fitbit Title": "Fitbit",
    "Devices Registered": "dispositivos registrados en el estudio",
    "Register Fitbit": "Registrar Fitbit",
    "Register New Fitbit Subtitle": "Asignar un nuevo dispositivo Fitbit al sistema",
    "In Use": "En uso",
    "Free": "Libres",
    "Maintenance": "Mantenimiento",
    "Inactive": "Inactivas",
    "Search Fitbit": "Buscar por código de pulsera o estado...",
    "Status": "ESTADO",
    "Register New Fitbit": "Registrar nueva Fitbit",
    "Automatic Code": "Código de dispositivo (Automático)",
    "Operational Status": "Estado operativo",
    "Save Fitbit": "Guardar Fitbit",
    "Fitbit Detail": "Detalle Fitbit",
    "Fitbit Full Info": "Información completa del dispositivo seleccionado.",
    "Delete Fitbit": "Eliminar Fitbit",
    "Error loading fitbits": "No se pudieron cargar las pulseras",
    "Create fitbit error": "No se pudo registrar la pulsera",
    "Fitbit registered": "Pulsera registrada correctamente.",
    "No Fitbits found": "No se encontraron dispositivos.",
    "Delete Fitbit Confirmation": "¿Eliminar la pulsera",
    "Delete Fitbit error": "No se pudo eliminar la pulsera",

    // Assignments
    "Assignments Title": "Asignaciones",
    "Assignments Registered": "asignaciones registradas en el estudio",
    "New Assignment": "Registrar nueva asignación",
    "New Assignment Subtitle": "Asignar un dispositivo Fitbit a un participante",
    "Search Assignment": "Buscar por código de participante, pulsera o estado...",
    "Start Date": "FECHA INICIO",
    "Estimated End Date": "FECHA FIN ESTIMADA",
    "Real End Date": "FECHA FIN REAL",
    "Select Participant": "Selecciona un participante",
    "Select Fitbit": "Selecciona una Fitbit",
    "Save Assignment": "Guardar asignación",
    "Edit Assignment": "Editar asignación",
    "Modify": "Modificar",
    "Save Changes": "Guardar cambios",
    "Delete Assignment": "Eliminar asignación",
    "Error loading assignments": "No se pudieron cargar las asignaciones",
    "Create assignment error": "No se pudo crear la asignación",
    "Assignment created successfully": "Asignación creada correctamente.",
    "Update assignment error": "No se pudo actualizar la asignación",
    "In Progress": "En curso",
    "No assignments found": "No se encontraron asignaciones.",
    "Select Participant Label": "Código de Participante",
    "Select a participant": "Selecciona un participante",
    "Select Fitbit Label": "Código de Fitbit",
    "Select a bracelet": "Selecciona una pulsera",
    "Real End Date Optional": "Fecha fin real (opcional)",
    "Edit Assignment Subtitle": "Modifica los campos necesarios de la asignación.",
    "Assignment Detail": "Detalle de asignación",
    "Assignment Detail Subtitle": "Información completa de la asignación seleccionada.",
    "Delete Assignment Confirmation": "¿Eliminar la asignación de",
    "Activa": "Activa",
    "Completada": "Completada",

    // Physiological Data
    "Physiological Data Title": "Datos fisiológicos",
    "Physiological Subtitle": "Consulta, filtra y analiza el histórico de monitorización",
    "All": "Todos",
    "Active": "Activo",
    "Completed": "Completado",
    "Export CSV": "Exportar a CSV",
    "Export Excel": "Exportar a Excel",
    "Clear Filters": "Limpiar filtros",
    "From": "Desde",
    "To": "Hasta",
    "Detailed Records": "Registros detallados",
    "Showing Filtered Records": "Mostrando {{count}} de {{total}} registros filtrados",
    "Variable": "VARIABLE",
    "Time": "HORA",
    "Value": "VALOR",
    "Previous": "← Anterior",
    "Next": "Siguiente →",
    "Page": "Página {{page}} de {{totalPages}}",
    "No Physiological Data": "No se encontraron datos para los filtros seleccionados.",
    "Selected plural": "seleccionados",
    "Clear selection": "Limpiar selección",
    "All (Clear selection)": "Todos (Limpiar selección)",
    "No results found": "No se encontraron resultados",
    "Error loading physiological data": "No se pudieron cargar los datos fisiológicos",
    "Search Variable": "Buscar variable...",
    "unit_min": "min",
    "unit_bpm": "lpm",
    "unit_resp": "resp/min",
    "unit_ms": "ms",
    "unit_km": "km",
    "unit_steps": "pasos",

    // Alerts
    "Alerts Title": "Alertas y Notificaciones",
    "Alerts Subtitle": "Supervisión automática de dispositivos.",
    "Active Count": "Activas ({{count}})",
    "Resolved History": "Historial Resueltas",
    "Critical": "CRÍTICAS",
    "Warnings": "ADVERTENCIAS",
    "Active Tray": "Bandeja de incidencias activas",
    "Resolved Tray": "Historial de incidencias resueltas",
    "Per Page": "por página",
    "Resolve": "Resolver",
    "Resolved": "Resuelta",
    "No Alerts": "No hay alertas registradas.",
    "Error loading alerts": "No se pudieron cargar las alertas",
    "Error resolving alert": "No se pudo marcar la alerta como resuelta",
    "SYNC_ERROR_title": "Error de sincronización",
    "SYNC_ERROR_msg": "No ha sido posible sincronizar los datos del participante. Revise la conexión e inténtelo de nuevo.",
    "NO_DATA_24H_title": "Sin datos >24 horas",
    "NO_DATA_24H_msg": "No se han recibido datos del participante en las últimas 24 horas. Compruebe que la pulsera está siendo utilizada y sincronizada correctamente.",
    "DEVICE_OFF_title": "Pulsera apagada",
    "DEVICE_OFF_msg": "La pulsera parece estar apagada o sin actividad. Solicite al participante que la encienda y sincronice con la aplicación Fitbit.",
    "LOW_BATTERY_title": "Batería <20%",
    "LOW_BATTERY_msg": "La batería de la pulsera es inferior al 20%. Se recomienda recargar el dispositivo para evitar pérdidas de datos.",
    "TOKEN_EXPIRED_title": "Token caducado",
    "TOKEN_EXPIRED_msg": "No se puede acceder a los datos del participante. Es necesario volver a autorizar la conexión con Google Health.",
    "DEVICE_UNLINKED_title": "Dispositivo desvinculado",
    "DEVICE_UNLINKED_msg": "La pulsera ya no está vinculada a la cuenta del participante. Compruebe la configuración de Fitbit y Google Health.",
    "NO_RECORDS_title": "Participante sin registros",
    "NO_RECORDS_msg": "No existen datos registrados para este participante. Compruebe que el proceso de vinculación se ha completado correctamente.",
    "HRV_UNAVAILABLE_title": "HRV no disponible",
    "HRV_UNAVAILABLE_msg": "No se ha podido obtener la variabilidad de la frecuencia cardíaca (HRV) para este día. Esto puede deberse a un tiempo de uso insuficiente durante el sueño o a una calidad de señal inadecuada.",
    "INSUFFICIENT_SLEEP_title": "Sueño insuficiente",
    "INSUFFICIENT_SLEEP_msg": "Se ha registrado un tiempo de sueño insuficiente para obtener todas las métricas fisiológicas.",
    "INSUFFICIENT_USAGE_title": "Tiempo de uso insuficiente",
    "INSUFFICIENT_USAGE_msg": "La pulsera ha sido utilizada menos de 18 horas durante el día. Algunas variables fisiológicas pueden estar incompletas.",

    // Exports
    "Exports Title": "Exportaciones",
    "Exports Subtitle": "Descarga conjuntos de datos globales para análisis estadístico.",
    "Export Notice": "Para exportar rangos o participantes específicos, utiliza los filtros avanzados en la sección de",
    "Participants Resource": "PARTICIPANTES",
    "Participants Desc": "Listado completo e información.",
    "Fitbits Resource": "FITBITS",
    "Fitbits Desc": "Estado y asignación de pulseras.",
    "Syncs Resource": "SINCRONIZACIONES",
    "Syncs Desc": "Historial de descargas y errores.",
    "Assignments Resource": "ASIGNACIONES",
    "Assigments Desc": "Histórico de asignaciones y uso de dispositivos.",
    "Alerts Resource": "ALERTAS",
    "Alerts Desc": "Supervisión automática de incidencias.",
    "Researchers Resource": "INVESTIGADORES",
    "Researchers Desc": "Listado de cuentas autorizadas en el sistema.",
    "Download CSV": "Descargar CSV",
    "Download Excel": "Descargar Excel",
    "Modal Title": "Filtros de Exportación:",
    "Modal Subtitle": "Selecciona los parámetros para refinar la descarga del archivo",
    "Study Status": "Estado del estudio",
    "All participants": "Todos los participantes",
    "All status": "Todos los estados",
    "All Fitbits": "Todas las Fitbits",
    "All alarm types": "Todos los tipos de alertas",
    "All priorities": "Todas las prioridades",
    "Status assignment": "Estado de asignación",
    "Synchronization date": "Fecha de sincronización",
    "Alarm type": "Tipo de alerta",
    "Priority": "Prioridad",
    "Detected": "Detectada",
    "High": "Alta",
    "Medium": "Media",
    "Download Filtered File": "Descargar Archivo Filtrado",
    "Latest Downloads": "Últimas descargas",
    "Logs History Desc": "Historial de los {{count}} últimos archivos exportados.",
    "Clear History": "Limpiar historial",
    "Resource": "Recurso",
    "Format": "Formato",
    "Date and Time": "Fecha y Hora",
    "Action": "Acción",
    "No Downloads": "No hay registros de descargas recientes.",
    "Records Count": "registros",
    "There is no information for the selected filters": "No hay información para los filtros seleccionados",
    "The date must not be later than today's date": "La fecha no debe ser posterior a la fecha de hoy",


    // Syncs
    "Syncs Title": "Sincronizaciones",
    "Syncs Subtitle": "Historial de descargas desde Google Health API y estado de cada intento.",
    "Clear History Btn": "Vaciar historial",
    "Update Data": "Actualizar datos",
    "Updating": "Actualizando...",
    "Success Metric": "ÉXITOS",
    "Error Metric": "ERRORES",
    "Total Metric": "TOTAL PROCESOS",
    "Successes": "Éxitos",
    "Errors": "Errores",
    "Sync ID": "ID REGISTRO",
    "Account": "CUENTA",
    "Start": "INICIO",
    "Result": "RESULTADO",
    "No Syncs": "No se encontraron sincronizaciones con los filtros aplicados.",
    "Error loading syncs": "No se pudieron cargar las sincronizaciones",
    "Clear history confirmation": "¿Estás seguro de que deseas vaciar todo el historial de sincronizaciones? Esta acción no se puede deshacer.",
    "Clear history error": "No se pudo vaciar el historial",
    "No account": "Sin cuenta",
    "Search Sync": "Buscar por cuenta de correo o resultado...",

    // Admin
    "Admin Title": "Gestionar investigadores",
    "Admin Subtitle": "Panel exclusivo para administradores: autoriza correos y administra cuentas de investigador.",
    "Researcher Email Input": "Correo electrónico investigador/a",
    "Authorize Btn": "Autorizar y verificar correo",
    "Authorized Researchers": "Investigadores autorizados",
    "Accounts Registered": "cuentas registradas",
    "Created": "CREADO",
    "Pending": "Pendiente",
    "No Researchers": "No hay investigadores registrados.",
    "Error loading researchers": "No se pudieron cargar los investigadores",
    "Create researcher error": "No se pudo dar de alta al investigador",
    "Email sent to researcher": "Correo enviado a investigador/a con email:",
    "pending acceptance": "pendiente de aceptación",
    "Delete researcher confirmation": "¿Estás seguro de que deseas eliminar al investigador",
    "Delete researcher error": "No se pudo eliminar el investigador",
    "Researcher deleted successfully": "Investigador eliminado con éxito",
    "Delete Researcher": "Eliminar investigador"
  }
};

export default es;