from django.urls import path
from .views import (
    google_login_view,
    google_callback_view,
    api_participants,
    api_fitbits,
    api_fitbits_create,
    api_fitbits_delete,
    api_synclogs,
    api_admin_login,
    api_researcher_login,
    api_auth_status,
    api_admin_create_researcher,
    api_admin_researchers,
    api_alerts,
    api_resolve_alert,
    api_physiological_data,
    api_export,
    api_logout,
    api_assignments,
    api_participants_list,
    api_fitbits_list,
    api_assignments_create,
    api_variable_types_list,
    api_admin_delete_researcher,
    api_clear_synclogs,
    api_researcher_request_code,
    api_researcher_verify_code,
    api_researcher_verify_registration,
    researcher_response_view,
    api_assignments_update,
    api_assignments_delete,
    api_fitbits_update_status,
    api_export_physiological_data,
)

urlpatterns = [
    path('auth/login/', google_login_view, name='google_login'),
    path('auth/callback/', google_callback_view, name='google_callback'),
    # API endpoints for frontend
    path('api/auth/status/', api_auth_status, name='api_auth_status'),
    path('api/auth/researcher/login/', api_researcher_login, name='api_researcher_login'),
    path('api/admin/researchers/delete/', api_admin_delete_researcher, name='api_admin_delete_researcher'),
    path('api/auth/logout/', api_logout, name='api_logout'),
    path('api/admin/login/', api_admin_login, name='api_admin_login'),
    path('api/admin/researchers/', api_admin_researchers, name='api_admin_researchers'),
    path('api/admin/researchers/create/', api_admin_create_researcher, name='api_admin_create_researcher'),
    path('api/auth/researcher/respond/', researcher_response_view, name='researcher_response'),
    path('api/auth/researcher/request-code/', api_researcher_request_code, name='api_researcher_request_code'),
    path('api/auth/researcher/verify-code/', api_researcher_verify_code, name='api_researcher_verify_code'),
    path('api/auth/researcher/verify-registration/', api_researcher_verify_registration, name='api_researcher_verify_registration'),
    path('api/alerts/<uuid:alert_id>/resolve/', api_resolve_alert, name='api_resolve_alert'),
    path('api/alerts/', api_alerts, name='api_alerts'),
    path('api/physiological-data/', api_physiological_data, name='api_physiological_data'),
    path('api/variable/types/list/', api_variable_types_list, name='api_variable_types_list'),
    path('api/export/physiological/data/', api_export_physiological_data, name='api_export_physiological_data'),
    path('api/export/', api_export, name='api_export'),
    path('api/participants/', api_participants, name='api_participants'),
    path('api/fitbits/', api_fitbits, name='api_fitbits'),
    path('api/fitbits/create/', api_fitbits_create, name='api_fitbits_create'), 
    path('api/fitbits/update/status/', api_fitbits_update_status, name='api_fitbits_update_status'),
    path('api/fitbits/delete/', api_fitbits_delete, name='api_fitbits_delete'),
    path('api/synclogs/', api_synclogs, name='api_synclogs'),
    path('api/clear/synclogs/', api_clear_synclogs, name='api_clear_synclogs'),
    path('api/assignments/', api_assignments, name='api_assignments'),
    path('api/participants/list/', api_participants_list, name='api_participants_list'),
    path('api/fitbits/list/', api_fitbits_list, name='api_fitbits_list'),
    path('api/assignments/create/', api_assignments_create, name='api_assignments_create'),
    path('api/assignments/update/', api_assignments_update, name='api_assignments_update'),
    path('api/assignments/delete/', api_assignments_delete, name='delete'),

]