name: Commits Syntax Checker

on:
  push:
  pull_request:

jobs:
  check:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate commit messages
        uses: webiny/action-conventional-commits@v1.3.0